apiVersion: apps/v1
kind: Deployment
metadata:
  name: lab4-front
  namespace: lab4
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lab4-front
  template:
    metadata:
      labels:
        app: lab4-front
    spec:
      containers:
      - name: lab4-front-container
        image: artem5252/lab4-svelte:latest
        ports:
        - containerPort: 3000