  apiVersion: v1
  kind: Service
  metadata:
    name: lab4-front-service
    namespace: lab4
  spec:
    selector:
      app: lab4-front
    ports:
    - port: 80      
      targetPort: 3000
    type: ClusterIP